# Generated by Django 3.2.13 on 2022-10-13 06:57

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
